version: '3'
services:
  db:
    image: 'mdillon/postgis:9.6'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
  backend:
    command: '/bin/bash -c "chmod +x /usr/src/app/docker-entrypoint.sh && /usr/src/app/docker-entrypoint.sh"'
    environment:
      DB_NAME: 'postgres'
      DB_PASS: 'postgres'
      DB_PORT: '5432'
      DB_SERVICE: 'postgres'
      DB_USER: 'postgres'
      DEBUG: 'false'
      GUNICORN_TIMEOUT: '900'
    expose:
      - '8000'
    image: 'queplanta/backend:latest'
    links:
      - 'db:postgres'
    ports:
      - '5001:8000'
      - '5000:9090'
    restart: always
    volumes:
      - ./backend:/usr/src/app
      - public:/usr/src/app/public
      - static:/usr/src/app/static
  frontend:
    environment:
      GRAPHQL_HOST: 'backend'
      GRAPHQL_PORT: '9090'
      HOST: '0.0.0.0'
      PORT: '3000'
    image: 'node:10'
    user: 'node'
    working_dir: /home/node/app
    volumes:
      - ./frontend:/home/node/app
    command: "./entrypoint.sh"
    links:
      - backend
    ports:
      - '7171:3000'
    restart: always

volumes:
    db:
    public:
    static:
